// export { default as DeleteAccountForm } fro../../oldcode/components/form/form-auth-delete-accountunt';
// export { default as EmailConfirmationForm } fro../../oldcode/components/form/form-auth-email-confirmationion';
// export { default as CompleteProfileForm } fro../../oldcode/components/form/form-auth-complete-profileile';
// export { default as FormAuthForgotPassword } from './form-auth-forgot-password';
export { default as LoginForm } from './form-auth-login';
export { default as RegisterForm } from './form-auth-register';
// export { default as ResetPasswordForm } from './form-auth-reset-password';

// // New Better Auth Forms
// export { default as ChangePasswordForm } from './form-change-password';
// export { default as ContactForm } from './form-contact-form';
// export { default as Search } from './form-home-search';
// export { default as LogoutLink } from './form-logout';
export { default as OnboardingForm } from './form-onboarding';
// export { default as AccountForm } from './form-profile-account';
// export { default as AdditionalInfoForm } from './form-profile-additional-info';
// export { default as BasicInfoForm } from './form-profile-basic-info';
// export { default as BillingDetailsForm } from './form-profile-billing-details';
// export { default as PresentationForm } from './form-profile-presentation';
// export { default as VerificationForm } from './form-profile-verification';
// export { default as FreelancerReportForm } from './form-report-freelancer';
// export { default as ReportIssueForm } from './form-report-issue';
// export { default as ServiceReportForm } from './form-report-service';
// export { default as AddModelReviewForm } from './form-reviews-create';
// export { default as ReviewStatsForm } from './form-reviews-stats';
// export { default as SaveForm } from './form-save';
// export { default as CancelServiceForm } from './form-service-cancel';
// export { default as AddServiceForm } from './form-service-create';
// export { default as EditServiceForm } from './form-service-edit';
// export { default as StartChatForm } from './form-start-chat';
